{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo4.Test_Credence_005 object at 0x000002CEE732EED0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_demo4.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "4398ed49-28e7-4b40-a50f-ff90268a6927-attachment.txt", "type": "text/plain"}], "start": 1690644138673, "stop": 1690644138673, "uuid": "3dda98b4-e569-42f5-8474-323c4d70c971", "historyId": "73dba635d40b2750531e7b84628f259a", "testCaseId": "73dba635d40b2750531e7b84628f259a", "fullName": "test_demo4.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_demo4"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "Akhil-PC"}, {"name": "thread", "value": "15664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo4"}]}