{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_demo3.Test_Credence_003 object at 0x000002CEE732DB90>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_demo3.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "f8d0b7d5-76c1-4fa8-95bf-92bcf06e31db-attachment.txt", "type": "text/plain"}], "start": 1690644138464, "stop": 1690644138464, "uuid": "19505e48-e350-4783-a833-b153c459a927", "historyId": "124e67ee4494dc75f3ce0a548e5b1263", "testCaseId": "124e67ee4494dc75f3ce0a548e5b1263", "fullName": "test_demo3.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_demo3"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "Akhil-PC"}, {"name": "thread", "value": "15664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo3"}]}